### ISSUE TITLE
ServiceAccount convenience functionality

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/k8s_config#6]
It would be nice to have a convenience functionality for creating service accounts:

```
k8s_resources:
- namespace: someplace
  service_accounts:
  - someaccount
```

Rather than:

```
k8s_resources:
- namespace: someplace
  resources:
  - definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: someaccount
```
